name: Backend CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22] # Node.js version

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Print Env Secret
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: | 
        echo "Secret 1 is: $MONGO_URI"
        echo "Secret 2 is: $JWT_SECRET"
        echo "Secret 3 is: $PORT"
      
    - run: pm2 stop all || true

    # Install dependencies for backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: | 
        npm install --global yarn
        yarn --version
        yarn install
      
    # Install dependencies for frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        df -h
        sudo rm -rf ./build
        yarn install
        yarn run build

    # Write backend .env
    -     # Write backend .env
    - name: Write backend .env from secret
      working-directory: ./backend
      run: |
        cat > .env <<EOF
        MONGO_URI=${{ secrets.MONGO_URI }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        PORT=${{ secrets.PORT }}
        NODE_ENV=production
        EOF

    # Run backend tests
    - name: Run Backend Tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: 5001
      working-directory: ./backend
      run: npm test

    # Start services with PM2
    - run: pm2 start ./backend/server.js --name backend
    - run: pm2 serve ./frontend/build 3000 --name frontend --spa